Repository GSG-G10/eventy, pull requests merged in 2021-10, with the labels that each got.

#4 adding file structure
  .gitignore
  client/.gitignore
  client/package.json
  client/public/assets/Eventy.png
  client/public/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/components/index.jsx
  client/src/index.css
  client/src/index.jsx
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Events/style.css
  client/src/pages/Landing/index.jsx
  client/src/pages/Landing/style.css
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/style.css
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/style.css
  client/src/pages/Register/index.jsx
  client/src/pages/Register/style.css
  client/src/pages/index.jsx
  client/src/utils/index.jsx
  package.json
  server/app.js
  server/controllers/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/connection/index.js
  server/database/queries/index.js
  server/index.js
  server/middlewares/index.js
  server/routes/index.js
  server/test/index.test.js
  server/utils/validation/index.js
Labels: Done

#85 84 edit git event query
  server/controllers/errors/server-error.js
  server/database/queries/events/all-events-query.js
  server/database/queries/events/get-event-id.js
  server/database/queries/events/get-events-category.js
  server/database/queries/events/get-exlusive-events.js
  server/database/queries/events/get-online-events.js
  server/database/queries/events/get-top-event.js
  server/database/queries/events/organization-events-query.js
Labels: Done

#83 Create stepper form to create event
  client/.eslintrc.json
  client/package.json
  client/src/App.jsx
  client/src/index.css
  client/src/pages/Organization/create-event/index.jsx
  client/src/pages/Organization/create-event/stepper.jsx
  client/src/pages/Organization/create-event/style .css
  client/src/pages/Organization/create-event/utils/categories.jsx
  client/src/pages/Organization/create-event/utils/get-step-content.jsx
  client/src/pages/Organization/index.jsx
  server/controllers/events/post-event.js
  server/database/queries/events/create-event.js
  server/utils/validation/create-event-schema.js
Labels: Done, Front-End

#89 add 'AS organizer' for organizer name to distinguish between names
  server/database/queries/events/all-events-query.js
  server/database/queries/events/get-event-id.js
  server/database/queries/events/get-events-category.js
  server/database/queries/events/get-exlusive-events.js
  server/database/queries/events/get-online-events.js
  server/database/queries/events/get-top-event.js
  server/database/queries/events/organization-events-query.js
Labels: Awaiting Review
