Repository GSG-G10/eventy, pull requests merged in 2021-11, with the labels that each got.

#88 Organization event card
  client/package.json
  client/src/App.jsx
  client/src/components/organization-event-card/index.jsx
  client/src/index.css
  client/src/pages/Organization/index.jsx
Labels: Done

#92 Create cover photo component
  client/src/pages/Organization/cover/index.jsx
  client/src/pages/Organization/cover/style.css
  client/src/pages/Organization/index.jsx
Labels: Done

#93 create events card and fix some eslint errors
  .gitignore
  client/package.json
  client/src/components/events-card/index.jsx
  client/src/components/events-card/style.css
  client/src/components/index.jsx
Labels: Awaiting Review

#97 Customize organization page components
  client/src/App.css
  client/src/App.jsx
  client/src/components/events-card/index.jsx
  client/src/components/organization-event-card/index.jsx
  client/src/index.css
  client/src/pages/Organization/cover/index.jsx
  client/src/pages/Organization/cover/style.css
  client/src/pages/Organization/create-event/index.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  server/controllers/auth/index.js
  server/controllers/auth/login/get-user-id.js
  server/controllers/index.js
  server/controllers/organizations/get-organization-by-id.js
  server/routes/index.js
Labels: Done

#98 86 event page
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/pages/Event/InfoCard/index.jsx
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
Labels: Awaiting Review, Front-End

#101 Cutomize organizations page
  client/package.json
  client/src/App.jsx
  client/src/pages/Event/InfoCard/index.jsx
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/organization-card.jsx
  server/database/queries/organizations/get-all-orgs.js
Labels: Done

#102 99 events page
  client/src/App.jsx
  client/src/components/events-card/index.jsx
  client/src/pages/Events/Loader/index.jsx
  client/src/pages/Events/Modal/CategoryFilter.jsx
  client/src/pages/Events/Modal/LocationFilter.jsx
  client/src/pages/Events/Modal/PriceSlider.jsx
  client/src/pages/Events/Modal/index.jsx
  client/src/pages/Events/Modal/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Events/style.css
Labels: Done

#107 Create a pop up to edit event for admin
  client/src/pages/Organization/create-event/index.jsx
  client/src/pages/Organization/create-event/stepper.jsx
  client/src/pages/Organization/edit-event/index.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/style.css
  client/src/pages/index.jsx
  client/src/utils/index.jsx
  server/controllers/events/update-event.js
  server/database/queries/events/update-event-query.js
  server/utils/validation/update-event-validation.js
Labels: Done

#106 105 login
  client/src/App.jsx
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/Login/style.css
  server/controllers/auth/login/index.js
  server/controllers/auth/sign-up/index.js
  server/database/queries/organizations/add-new-org.js
  server/middlewares/setCookies.js
Labels: Done

#109 Edit styles and responsive design
  client/src/components/events-card/index.jsx
  client/src/pages/Event/InfoCard/index.jsx
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Events/Modal/index.jsx
  client/src/pages/Organization/edit-event/index.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  client/src/pages/Organization/style.css
  client/src/pages/Organizations/organization-card.jsx
  client/src/pages/Register/Login/index.jsx
  server/controllers/auth/login/get-user-id.js
Labels: Awaiting Review

#113 create sign up
  client/src/pages/Register/SignUp/Categories.jsx
  client/src/pages/Register/SignUp/Password.jsx
  client/src/pages/Register/SignUp/index.jsx
  client/src/pages/Register/SignUp/style.css
  client/src/pages/Register/index.jsx
  server/utils/validation/signup-schema-validation.js
Labels: Awaiting Review, Front-End

#112 Handle error pages
  client/src/App.jsx
  client/src/pages/Errors/404/index.jsx
  client/src/pages/Errors/404/style.css
  client/src/pages/Errors/500/index.jsx
  client/src/pages/Errors/500/style.css
  client/src/pages/Errors/index.jsx
  client/src/pages/Events/Modal/CategoryFilter.jsx
  client/src/pages/Events/Modal/LocationFilter.jsx
  client/src/pages/Events/Modal/PriceSlider.jsx
  client/src/pages/Organization/create-event/stepper.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Organizations/index.jsx
Labels: Done

#114 110 join event form
  client/src/pages/Event/InfoCard/index.jsx
  client/src/pages/Event/InfoCard/style.css
  client/src/pages/Event/JoinEvent/index.jsx
  client/src/pages/Event/JoinEvent/style.css
  client/src/pages/Event/JoinEvent/styles.js
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Organization/organization-event-card/index.jsx
  server/controllers/attendance/index.js
  server/database/queries/attendance/get-attendance.js
Labels: Awaiting Review

#95 create header
  client/src/App.jsx
  client/src/components/Header/EVENTY_logo.png
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/components/index.jsx
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/SignUp/index.jsx
  client/src/pages/Register/index.jsx
Labels: Awaiting Review

#119 create top events component
  client/package.json
  client/src/components/Carousel/index.jsx
  client/src/components/index.jsx
  client/src/pages/Landing/Top-events/index.jsx
Labels: Awaiting Review, Front-End

#117 Create register component
  client/src/App.jsx
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/pages/Landing/Advertisments/Advertisment1.jsx
  client/src/pages/Organization/cover/index.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/Login/style.css
  client/src/pages/Register/SignUp/Password.jsx
  client/src/pages/Register/SignUp/index.jsx
  client/src/pages/Register/SignUp/style.css
  client/src/pages/Register/index.jsx
  server/controllers/auth/sign-up/index.js
  server/controllers/organizations/get-organization-by-id.js
  server/utils/validation/signup-schema-validation.js
Labels: Awaiting Review

#124 121 footer and edit style
  client/src/App.jsx
  client/src/components/Footer/index.jsx
  client/src/components/Footer/style.css
  client/src/components/events-card/index.jsx
  client/src/components/events-card/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Organization/create-event/index.jsx
  client/src/pages/Organization/create-event/stepper.jsx
  client/src/pages/Organization/create-event/utils/get-step-content.jsx
  client/src/pages/Organization/edit-event/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  server/app.js
  server/controllers/events/all-events.js
  server/database/config/fakeData.sql
  server/utils/validation/update-event-validation.js
Labels: Done

#126 edit landing page
  client/src/components/Carousel/index.jsx
  client/src/pages/Events/Loader/index.jsx
  client/src/pages/Landing/About/index.jsx
  client/src/pages/Landing/Exclusive-events/index.jsx
  client/src/pages/Landing/Online-events/index.jsx
  client/src/pages/Landing/Top-events/index.jsx
  client/src/pages/Register/index.jsx
  client/src/pages/Register/style.css
Labels: Awaiting Review

#127 Fix bugs
  client/src/App.jsx
  client/src/components/Footer/style.css
  client/src/components/Header/index.jsx
  client/src/components/events-card/index.jsx
  client/src/pages/Events/index.jsx
  client/src/pages/Events/style.css
  client/src/pages/Landing/Exclusive-events/index.jsx
  client/src/pages/Landing/Online-events/index.jsx
  client/src/pages/Landing/Top-events/index.jsx
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/organization-card.jsx
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/index.jsx
Labels: Awaiting Review

#123 Deployment Edits
  client/package.json
  client/src/components/Carousel/index.jsx
  client/src/components/Footer/style.css
  client/src/components/Header/index.jsx
  client/src/components/events-card/index.jsx
  client/src/index.css
  client/src/pages/Event/JoinEvent/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Events/Modal/LocationFilter.jsx
  client/src/pages/Events/Modal/index.jsx
  client/src/pages/Events/Modal/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Events/style.css
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/SignUp/index.jsx
  package.json
  server/controllers/attendance/index.js
  server/database/config/fakeData.sql
  server/database/queries/attendance/index.js
  server/database/queries/attendance/upadte-attendance.js
  server/database/queries/index.js
  server/utils/validation/create-event-schema.js
Labels: Done

#131 130 style refactor
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/components/Header/styles.js
  client/src/components/events-card/index.jsx
  client/src/components/events-card/styles.js
  client/src/pages/Errors/500/index.jsx
  client/src/pages/Errors/500/style.css
  client/src/pages/Event/InfoCard/style.css
  client/src/pages/Event/JoinEvent/index.jsx
  client/src/pages/Event/JoinEvent/style.css
  client/src/pages/Event/JoinEvent/styles.js
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Events/styles.js
  client/src/pages/Landing/About/index.jsx
  client/src/pages/Landing/About/style.css
  client/src/pages/Landing/Advertisments/Advertisment1.jsx
  client/src/pages/Landing/Advertisments/Advertisment2.jsx
  client/src/pages/Landing/Advertisments/style.css
  client/src/pages/Landing/Exclusive-events/index.jsx
  client/src/pages/Landing/Online-events/index.jsx
  client/src/pages/Landing/Top-events/index.jsx
  client/src/pages/Landing/index.jsx
  client/src/pages/Landing/style.css
  client/src/pages/Register/Login/style.css
Labels: Awaiting Review

#129 Edit date input to start from today
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Organization/create-event/stepper.jsx
  client/src/pages/Organization/create-event/style .css
  client/src/pages/Organization/create-event/utils/get-step-content.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  client/src/pages/Organization/organization-event-card/styles.js
  client/src/pages/Organization/style.css
  client/src/pages/Organization/styles.js
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/organization-card.jsx
  client/src/pages/Organizations/style.css
  client/src/pages/Organizations/styles.js
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/Login/style.css
  client/src/pages/Register/SignUp/Password.jsx
  client/src/pages/Register/SignUp/index.jsx
  client/src/pages/Register/index.jsx
Labels: Done

#136 Edit style for landing page
  client/src/components/events-card/index.jsx
  client/src/pages/Landing/style.css
  client/src/pages/Register/SignUp/style.css
  client/src/pages/Register/index.jsx
  client/src/pages/Register/style.css
Labels: Done

#135 132 categories bug
  client/src/components/events-card/index.jsx
  client/src/pages/Organizations/organization-card.jsx
  client/src/pages/Organizations/style.css
  server/controllers/auth/sign-up/index.js
  server/controllers/events/post-event.js
  server/controllers/events/update-event.js
  server/database/config/fakeData.sql
Labels: Done

#137 edit-event-image
  client/src/pages/Event/index.jsx
Labels: Done

#141 Edit colors
  client/src/index.css
  client/src/pages/Landing/style.css
  client/src/pages/Organization/create-event/index.jsx
  client/src/pages/Organization/create-event/style.js
  client/src/pages/Organization/edit-event/index.jsx
  client/src/pages/Organization/index.jsx
  client/src/pages/Organization/organization-event-card/index.jsx
  client/src/pages/Organization/organization-event-card/styles.js
  client/src/pages/Organization/style.css
  client/src/pages/Organization/styles.js
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/organization-card.jsx
  client/src/pages/Organizations/style.css
  client/src/pages/Organizations/styles.js
Labels: Awaiting Review

#142 change event and register pages style
  client/public/assets/icon.png
  client/public/index.html
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/components/events-card/index.jsx
  client/src/pages/Event/InfoCard/index.jsx
  client/src/pages/Event/InfoCard/style.css
  client/src/pages/Event/JoinEvent/index.jsx
  client/src/pages/Event/JoinEvent/style.css
  client/src/pages/Event/JoinEvent/styles.js
  client/src/pages/Event/index.jsx
  client/src/pages/Event/style.css
  client/src/pages/Events/index.jsx
  client/src/pages/Events/style.css
  client/src/pages/Events/styles.js
  client/src/pages/Landing/style.css
  client/src/pages/Organization/cover/style.css
  client/src/pages/Organization/create-event/index.jsx
  client/src/pages/Organization/style.css
  client/src/pages/Organizations/index.jsx
  client/src/pages/Organizations/style.css
  client/src/pages/Register/Login/index.jsx
  client/src/pages/Register/Login/style.css
  client/src/pages/Register/SignUp/Categories.jsx
  client/src/pages/Register/SignUp/Password.jsx
  client/src/pages/Register/SignUp/index.jsx
  client/src/pages/Register/index.jsx
Labels: Done
